steps:

  - name: ":hammer: Build"
    command: docker build . -t ${DOCKER_IMAGE_REPO}

  - name: ":cloud: Publish to ECR"
    command: > 
     $(aws ecr get-login --no-include-email --region ap-southeast-2) && 
     docker push ${DOCKER_IMAGE_REPO}
