steps:

  - name: ":maven: Build Atlas"
    env:
      MAVEN_OPTS: "-Xmx2048m -XX:MaxPermSize=512m -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    command: >
      cd ${BUILDKITE_BUILD_CHECKOUT_PATH} && rm -fr atlas &&
      git clone -b ${ATLAS_TAG} --single-branch --depth 1 https://github.com/apache/atlas atlas &&
      cd atlas &&
      mvn clean package -Pdist -DskipTests -Dmaven.artifact.threads=20 &&
      mv distro/target/apache-atlas-*-bin.tar.gz ${BUILDKITE_BUILD_CHECKOUT_PATH} &&
      ls -al ${BUILDKITE_BUILD_CHECKOUT_PATH}

  - name: ":maven: Build DynamoDB"
    env:
      SHADE_PLUGIN: >
        <profile><id>shade</id><build><plugins>
        <plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-shade-plugin</artifactId>
        <version>3.1.0</version><executions><execution><phase>package</phase><goals><goal>shade</goal></goals>
        <configuration><relocations><relocation><pattern>com.google</pattern>
        <shadedPattern>com.shaded.google</shadedPattern></relocation></relocations>
        <artifactSet><includes><include>com.google.guava:*</include></includes></artifactSet>
        </configuration></execution></executions></plugin></plugins></build></profile>
    command: >
      cd ${BUILDKITE_BUILD_CHECKOUT_PATH} && rm -fr dynamodb-janusgraph &&
      git clone -b ${DYNAMODB_TAG} --single-branch --depth 1 https://github.com/awslabs/dynamodb-janusgraph-storage-backend dynamodb-janusgraph &&
      cd dynamodb-janusgraph &&
      sed -i -e "s#<profiles>#<profiles>${SHADE_PLUGIN}#" pom.xml &&
      mvn clean package -Pshade -DskipTests -Dmaven.artifact.threads=20 &&
      mv target/dynamodb-janusgraph-storage-backend*.jar ${BUILDKITE_BUILD_CHECKOUT_PATH} &&
      rm target/dependencies/guava*.jar &&
      tar vcfz ${BUILDKITE_BUILD_CHECKOUT_PATH}/dynamodb-janusgraph-deps.tgz target/dependencies/*.jar &&
      ls -al ${BUILDKITE_BUILD_CHECKOUT_PATH}
